### ISSUE TITLE
Add `InsertBraces` (clang-format 15)

### ISSUE THREAD

**Issue by petertorelli** [petertorelli/clang-format-barr-c#4]
Barr C requires single line (if, else, for, do, and while) control to have braces. `clang-format` version 15 supports this, but is not widely available yet (brew, apt [ubuntu], snap). Will add this once it diffuses into the wild.

**Comment by gvieralopez** [comment]
I just added it in https://github.com/petertorelli/clang-format-barr-c/pull/5.
